name: Node.js CI
"on":
  push:
    branches:
      - master
      - dependabot/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - name: Check that the latest CommonJS target has been checked in
        run: |
          npm run build
          git diff-index --quiet HEAD
      - run: npm test
